#version 430 core

// local workgroup with 8x8x1 
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// run a O(voxelsizeof(A)) algorithm to check the voxel space's intersection
// we need transform the A space's voxels to B space 
struct VoxelInfo{
	int dimx;
	int dimy;
	int dimz;
};

uniform VoxelInfo voxelInfoA;

layout(binding = 0, r32ui) uniform readonly uimage3D voxelA;

layout(std430, binding = 0) buffer Center{
	int cx;
	int cy;
	int cz;

	int voxel_count;
};

int dot_int(ivec3 a, ivec3 b) {
    return a.x * b.x + a.y * b.y + a.z * b.z;
}
void main(){
	ivec3 voxelCoordA = ivec3(gl_GlobalInvocationID.xy, 0);
	if(voxelCoordA.x >= voxelInfoA.dimx || voxelCoordA.y >= voxelInfoA.dimy) return;

	// for each compute shader invocation
	// we check a strip of zs'

	for(int zi = 0; zi < (voxelInfoA.dimz + 31) / 32; ++zi){
		uint dataA = imageLoad(voxelA, ivec3(voxelCoordA.xy, zi)).r;
		int x = voxelCoordA.x;
		int y = voxelCoordA.y;
		for(int zr = 0; zr < 32; ++zr){
			int z = zi * 32 + zr;
			if(z >= voxelInfoA.dimz) break;
			if(((dataA >> zr) & 1u) == 0u) continue;
			
			atomicAdd(cx,x);
			atomicAdd(cy,y);
			atomicAdd(cz,z);
			atomicAdd(voxel_count,1);
		}
	}
}