#version 430 core

// local workgroup with 8x8x1 
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
// run a O(voxelsizeof(A)) algorithm to check the voxel space's intersection
// we need transform the A space's voxels to B space 
struct VoxelInfo{
	int dimx;
	int dimy;
	int dimz;

	// use world space as voxel space
	// voxelspaces' left bottom corner
	int corner_x;
	int corner_y;
	int corner_z;
};

uniform VoxelInfo voxelInfoA;

uniform int voxel_size_p;
uniform int voxel_size_q;

layout(binding = 2, r32ui) uniform readonly uimage3D Collisions;

// the 2nd pass 
layout(std430, binding = 4) readonly buffer Approximate_Attribute{
	int point_x;
	int point_y;
	int point_z;

	int normal_x;
	int normal_y;
	int normal_z;

	int voxel_count;

	int nx, mx;
	int ny, my;
	int nz, mz;
};

layout(std430, binding = 5) buffer Penetration{
	int max_penetrate;
	int min_penetrate;
};


uniform int splitting;
struct currentCenter{
	int x;
	int y;
	int z;
};

uniform currentCenter currentCenterA;

int dot_int(ivec3 a, ivec3 b) {

    return a.x * b.x + a.y * b.y + a.z * b.z;
}
void main(){
	ivec3 voxelCoordA = ivec3(gl_GlobalInvocationID.xy, 0);
	if(voxelCoordA.x >= voxelInfoA.dimx || voxelCoordA.y >= voxelInfoA.dimy) return;

	// for each compute shader invocation
	// we check a strip of zs'

	// transform the A space's voxels to B space
	ivec3 cornerA = ivec3(voxelInfoA.corner_x, voxelInfoA.corner_y, voxelInfoA.corner_z);
	for(int zi = 0; zi < (voxelInfoA.dimz + 31) / 32; ++zi){
		uint dataA = imageLoad(Collisions, ivec3(voxelCoordA.xy, zi)).r;
		//TODO: align the bitstring with offset of 32
		// to achive the collision checking in one and operation
		for(int zr = 0; zr < 32; ++zr){
			int z = zi * 32 + zr;
			if(z >= voxelInfoA.dimz) break;
			if(((dataA >> zr) & 1u) == 0u) continue;
			ivec3 coordA = ivec3(voxelCoordA.xy, z);
			
			//collide...
			int index = 0;
			if(coordA.x >= currentCenterA.x) index |= (1<<0);
			if(coordA.y >= currentCenterA.y) index |= (1<<1);
			if(coordA.z >= currentCenterA.z) index |= (1<<2);
			if(splitting != 0 && (index) != (splitting-1)) continue;
	

			// get the local normal (3x3x3 central difference)
			ivec3 center = ivec3(point_x, point_y, point_z);
			ivec3 normals = ivec3(normal_x, normal_y, normal_z);
			int dis = voxel_count * dot_int(coordA,normals) - dot_int(center,normals);
			atomicMax(max_penetrate, dis);
			atomicMin(min_penetrate, dis);

		}
	}

}