#version 430 core

// local workgroup with 8x8x8
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(std430, binding = 0) readonly buffer triangleBuffer{
	float triangles[];
};

layout(std430, binding = 1) readonly buffer normalBuffer{
	float normals[];
};
layout(binding = 0, r32f) uniform image3D distance_field;
// the voxel space is [0,1]^3

uniform int df_resolution;
uniform int vertex_count;
vec3 projToLineSeg(vec3 p,vec3 a,vec3 b){
	vec3 ab = b - a;// ab

	float t = dot(p - a,ab) / dot(ab,ab);
	return a + ab * clamp(t,0.0,1.0);
}

void main(){
	ivec3 voxelCoord = ivec3(gl_GlobalInvocationID.xyz);
	if(voxelCoord.x >=  df_resolution|| voxelCoord.y >=  df_resolution|| voxelCoord.z >= df_resolution) return;
	vec3 p = vec3(voxelCoord.xyz) / float(df_resolution-1);
	float d = 100;
	bool fg = false;
	for(int i = 0; i < vertex_count; i += 3){
		vec3 v0 = vec3(triangles[i * 3 + 0],triangles[i * 3 + 1],triangles[i * 3 + 2]);
		vec3 v1 = vec3(triangles[i * 3 + 3],triangles[i * 3 + 4],triangles[i * 3 + 5]);
		vec3 v2 = vec3(triangles[i * 3 + 6],triangles[i * 3 + 7],triangles[i * 3 + 8]);		
		d = min(d,distance(p,v1));
		d = min(d,distance(p,v0));
		d = min(d,distance(p,v2));
		//3 triangle edge
		d = min(d,distance(p,projToLineSeg(p,v1,v2)));
		d = min(d,distance(p,projToLineSeg(p,v0,v2)));
		d = min(d,distance(p,projToLineSeg(p,v0,v1)));
		
		// check interior 
		vec3 v = v1 - v0;
		vec3 w = v2 - v0;
		vec3 x = p - v0;

		vec3 n = cross(v,w);
		if(dot(n,n) < 1e-6) continue;
		n = normalize(n);
		x = (x - dot(x,n) * n);
		
		// x = c1 * v + c2 * w
		// x * v = c1 * vv + c2 * wv
		// x * w = c1 * wv + c2 * ww
		float vv = dot(v,v);
		float wv = dot(w,v);
		float ww = dot(w,w);

		float xv = dot(x,v);
		float xw = dot(x,w);

		float det = vv * ww - (wv * wv);

		float c1 = xv * ww - xw * wv;
		float c2 = xw * vv - xv * wv;
		if(det < 1e-6) continue;
		c1 /= det, c2 /= det;
		if(c1 + c2 <= 1 && c1 >= 0 && c2 >= 0){
			d = min(d,abs(dot(p - v0,n)));
		}
	}
	imageStore(distance_field,voxelCoord,vec4(d,1,1,1));
}