#version 430 core

// local workgroup with 8x8x8
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(std430, binding = 0) readonly buffer triangleBuffer{
	float triangles[];
};

layout(std430, binding = 1) readonly buffer normalBuffer{
	vec3 normals[];
};
layout(binding = 0, r32f) uniform image3D distance_field;
// the voxel space is [0,1]^3

uniform int df_resolution;
uniform int vertex_count;
void main(){
	ivec3 voxelCoord = ivec3(gl_GlobalInvocationID.xyz);
	if(voxelCoord.x >=  df_resolution|| voxelCoord.y >=  df_resolution|| voxelCoord.z >= df_resolution) return;
	vec3 pos = vec3(voxelCoord.xyz) / float(df_resolution-1);
	float d = 100;
	bool fg = false;
	for(int i = 0; i < vertex_count; i++){
		float dis = distance(pos,vec3(triangles[i * 3 + 0],triangles[i * 3 + 1],triangles[i * 3 + 2]));
		d = min(dis,d);
	}
	// d = dot(pos,vec3(.5));
	imageStore(distance_field,voxelCoord,vec4(d,1,1,1));
}