#version 430 core

// local workgroup with 8x8x1 
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// run a O(voxelsizeof(A)) algorithm to check the voxel space's intersection
// we need transform the A space's voxels to B space 
struct VoxelInfo{
	int dimx;
	int dimy;
	int dimz;

	// use world space as voxel space
	// voxelspaces' left bottom corner
	int corner_x;
	int corner_y;
	int corner_z;
};

uniform VoxelInfo voxelInfoA;

uniform int voxel_size_p;
uniform int voxel_size_q;

layout(binding = 0, r32ui) uniform readonly uimage3D voxelA;
layout(binding = 1) buffer RAY_DATA{
	vec3 direct;
	vec3 ori;
	float pad0;
	float il;
	float ir;
	uint mutex;
	int hit;
};

void setInterval(float l, float r){
	while(atomicExchange(mutex,1u) == 0u){
		ir = min(ir,r);
	}

	atomicExchange(mutex,0u);
}

float intvR[3];
float intvL[3];
void main(){
	ivec3 voxelCoordA = ivec3(gl_GlobalInvocationID.xy, 0);
	if(voxelCoordA.x >= voxelInfoA.dimx || voxelCoordA.y >= voxelInfoA.dimy) return;

	ivec3 cornerA = ivec3(voxelInfoA.corner_x, voxelInfoA.corner_y, voxelInfoA.corner_z);
	for(int zi = 0; zi < (voxelInfoA.dimz + 31) / 32; ++zi){
		uint dataA = imageLoad(voxelA, ivec3(voxelCoordA.xy, zi)).r;
		for(int zr = 0; zr < 32; ++zr){
			int z = zi * 32 + zr;
			if(z >= voxelInfoA.dimz) break;
			if(((dataA >> zr) & 1u) == 0u) continue;
			vec3 coord = vec3(voxelCoordA.xy, z);
			vec3 coordM = coord;
			coordM += vec3(1.0);
			coordM += cornerA;
			coordM *= float(voxel_size_p) / float(voxel_size_q);
			coord += cornerA;
			coord *= float(voxel_size_p) / float(voxel_size_q);

			vec3 ray_orig = ori;
			vec3 ray_dir = direct;
			float ill = il;
			float irr = ir;

			for (int axis = 0; axis < 3; axis++) {
				float adinv = 1.0 / ray_dir[axis];

				float t0 = (coord[axis] - ray_orig[axis]) * adinv;
				float t1 = (coordM[axis] - ray_orig[axis]) * adinv;
				if (t0 > t1) {
					float tt = t0;
					t0 = t1;
					t1 = tt;
				}
				if (t0 > ill) ill = t0;
				if (t1 < irr) irr = t1;
				if (irr <= ill)
					continue;
			}
			setInterval(ill,irr);
			atomicExchange(hit,1);
		}
	}

}