#version 430 core

// local workgroup with 8x8x1 
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// run a O(voxelsizeof(A)) algorithm to check the voxel space's intersection
// we need transform the A space's voxels to B space 
struct VoxelInfo{
	int dimx;
	int dimy;
	int dimz;

	// use world space as voxel space
	// voxelspaces' left bottom corner
	int corner_x;
	int corner_y;
	int corner_z;
};

uniform VoxelInfo voxelInfoA;

layout(binding = 2, r32ui) uniform readonly uimage3D Collisions;

struct currentCenter{
	int x;
	int y;
	int z;
};

uniform currentCenter currentCenterA;
struct collision_att{
	int point_x;
	int point_y;
	int point_z;
	
	int normal_x;
	int normal_y;
	int normal_z;

	int voxel_count;
};
layout(std430, binding = 5) buffer splitAtrribute{
	int point_x[8];
	int point_y[8];
	int point_z[8];
	
	int normal_x[8];
	int normal_y[8];
	int normal_z[8];

	int voxel_count[8];
};
int occupied(ivec3 v){
	if(v.x >= voxelInfoA.dimx || v.y >= voxelInfoA.dimy || v.z >= voxelInfoA.dimz) return 0;
	int zi = v.z / 32;
	uint data = imageLoad(Collisions, ivec3(v.xy, zi)).r;
	int zr = v.z % 32;
	if(((data >> zr) & 1u) == 0) return 0;
	else return 1;
}
void main(){
	ivec3 voxelCoordA = ivec3(gl_GlobalInvocationID.xy, 0);
	if(voxelCoordA.x >= voxelInfoA.dimx || voxelCoordA.y >= voxelInfoA.dimy) return;

	// for each compute shader invocation
	// we check a strip of zs'

	// transform the A space's voxels to B space
	ivec3 cornerA = ivec3(voxelInfoA.corner_x, voxelInfoA.corner_y, voxelInfoA.corner_z);
	for(int zi = 0; zi < (voxelInfoA.dimz + 31) / 32; ++zi){
		uint dataA = imageLoad(Collisions, ivec3(voxelCoordA.xy, zi)).r;
		//TODO: align the bitstring with offset of 32
		// to achive the collision checking in one and operation
		for(int zr = 0; zr < 32; ++zr){
			int z = zi * 32 + zr;
			if(z >= voxelInfoA.dimz) break;
			if(((dataA >> zr) & 1u) == 0u) continue;
			
			//collide...

			// get the local normal (3x3x3 central difference)
			ivec3 coordA = ivec3(voxelCoordA.xy, z);

			int index = 0;
			if(coordA.x >= currentCenterA.x) index |= (1<<0);
			if(coordA.y >= currentCenterA.y) index |= (1<<1);
			if(coordA.z >= currentCenterA.z) index |= (1<<2);
			
			atomicAdd(normal_x[index],(occupied(coordA + ivec3(1,0,0)) - occupied(coordA + ivec3(-1,0,0))));
			atomicAdd(normal_y[index],(occupied(coordA + ivec3(0,1,0)) - occupied(coordA + ivec3(0,-1,0))));
			atomicAdd(normal_z[index],(occupied(coordA + ivec3(0,0,1)) - occupied(coordA + ivec3(0,0,-1))));

			atomicAdd(point_x[index],coordA.x);
			atomicAdd(point_y[index],coordA.y);
			atomicAdd(point_z[index],coordA.z);
			atomicAdd(voxel_count[index],1);
		}
	}

}